services:
  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    # Define um nome para o container para facilitar a identificação
    container_name: gestao_escolar_api
    # Mapeia a porta 8000 do seu computador (host) para a porta 8000 do container
    ports:
      - "8000:8000"
    # Monta o diretório atual do projeto dentro do container no diretório /app
    # Isso tem dois benefícios principais:
    # 1. Persistência de dados: O arquivo do banco de dados SQLite (escola.db) será criado no seu diretório local, sobrevivendo a reinicializações do container.
    # 2. Hot-Reload: Como o uvicorn está rodando com --reload, qualquer alteração que você fizer no código local será refletida instantaneamente no container.
    volumes:
      - .:/app